{% set name = "amundsen-databuilder" %}
{% set version = "7.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amundsen-databuilder-{{ version }}.tar.gz
  sha256: b03578fe09764ae909ee51c870f003de348230f9db20e7968aaf40227aef0c76

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - elasticsearch >=6.2.0,<8.0
    - elasticsearch-dsl >=7.4.0
    - neo4j-python-driver >=4.4.5,<5.0 # neo4j-driver same as neo4j-python-driver
    - requests >=2.25.0,<3.0
    - freezegun >=1.1.0
    - atomicwrites >=1.1.5
    - more-itertools >=4.2.0
    - pluggy >=0.6.0
    - py >=1.10.0
    - pyhocon >=0.3.42
 # pyhocon 0.3.59 has requirement pyparsing~=2.0
    - pyparsing >=2.2.0,<3.0
    - sqlalchemy >=1.3.6
    - wheel >=0.31.1
    - pytz >=2018.4
    - statsd >=3.2.1
    - retrying >=1.3.3
    - unicodecsv >=0.14.1,<1.0
    - httplib2 >=0.18.0
    - unidecode
    - jinja2 >=2.10.0,<4
    - pandas >=0.21.0,<1.5.0
    - responses >=0.10.6
    - jsonref ==0.2
    - amundsen-common >=0.16.0
    - amundsen-rds ==0.0.7

test:
  imports:
    - databuilder
    - example

# Pip check disabled
# amundsen-databuilder 7.4.3 requires neo4j-driver, which is not installed.    

#  commands:
#    - pip check
#  requires:
#    - pip    

about:
  home: https://www.github.com/amundsen-io/amundsen/tree/main/databuilder
  summary: Amundsen Data builder
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
